### ISSUE TITLE
Unwanted files in commits because of pre-commit prettier

### ISSUE THREAD

**Issue by AlexandrHoroshih** [solid-soda/scripts#29]
When i created new commit via `yarn soda cz`, i have found unwanted files in my commits.

Way to reproduce: change few files, `git add` only one of them, then do  `yarn soda cz` and create an commit. Result: all changed files are committed.

As i found out, it happens because of auto-prettier and then auto staging on **all** files before creating an commit, not just the ones, you **explicitly** added to staging.
Its kinda not cool.

Still an awesome package, though

**Comment by igorkamyshev** [comment]
Sorry for long answer. Will be released in @solid-soda/scipts@2.0.0

**Comment by igorkamyshev** [comment]
You can track it here https://github.com/solid-soda/scripts/pull/30
